# Generated by Django 5.2.15 on 2026-06-21 14:15

import django.db.models.deletion
import review.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folders', '0005_checklistitem_is_flagged_checklistitem_review_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(max_length=500, upload_to=review.models.certificate_path)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='folders.coursefolder')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
