# Generated by Django 5.2.15 on 2026-06-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('phase', models.CharField(choices=[('GENERAL', 'General'), ('MID', 'Mid-term'), ('FINAL', 'Final-term')], max_length=10)),
                ('is_required', models.BooleanField(default=True)),
                ('allows_samples', models.BooleanField(default=False, help_text='Item is graded as Worst/Average/Best samples.')),
                ('is_removable', models.BooleanField(default=False, help_text='Count-variable item faculty may add/remove (e.g. extra quizzes).')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
