# Generated by Django 5.2.15 on 2026-06-21 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_course'),
        ('folders', '0002_seed_checklist_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('MID_SUBMITTED', 'Mid-term submitted'), ('MID_APPROVED', 'Mid-term approved'), ('FINAL_SUBMITTED', 'Final-term submitted'), ('CERTIFIED', 'Certified')], default='DRAFT', max_length=20)),
                ('mid_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('mid_approved_at', models.DateTimeField(blank=True, null=True)),
                ('final_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='academics.course')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('phase', models.CharField(choices=[('GENERAL', 'General'), ('MID', 'Mid-term'), ('FINAL', 'Final-term')], max_length=10)),
                ('is_required', models.BooleanField(default=True)),
                ('allows_samples', models.BooleanField(default=False)),
                ('is_removable', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AVAILABLE', 'Available'), ('NOT_APPLICABLE', 'Not applicable')], default='PENDING', max_length=20)),
                ('na_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='folders.checklisttemplateitem')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='folders.coursefolder')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
