# Generated by Django 5.2.15 on 2026-06-21 10:14

import django.db.models.deletion
import folders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0003_coursefolder_checklistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_kind', models.CharField(choices=[('NONE', '—'), ('WORST', 'Worst'), ('AVERAGE', 'Average'), ('BEST', 'Best')], default='NONE', max_length=10)),
                ('file', models.FileField(max_length=500, upload_to=folders.models.item_file_path)),
                ('original_name', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('thumbnail', models.FileField(blank=True, max_length=500, null=True, upload_to=folders.models.item_thumb_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='folders.checklistitem')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at', 'id'],
            },
        ),
    ]
