# Generated by Django 5.2.15 on 2026-06-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0004_itemfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursefolder',
            name='final_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursefolder',
            name='final_return_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursefolder',
            name='mid_return_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coursefolder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('MID_SUBMITTED', 'Mid-term submitted'), ('MID_APPROVED', 'Mid-term approved'), ('FINAL_SUBMITTED', 'Final-term submitted'), ('FINAL_APPROVED', 'Final-term approved'), ('CERTIFIED', 'Certified')], default='DRAFT', max_length=20),
        ),
    ]
