# Generated by Django 5.2.15 on 2026-06-21 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=30)),
                ('credit_hours', models.PositiveSmallIntegerField(default=3)),
                ('program', models.CharField(help_text='e.g. BSCS, BSSE, BSIT', max_length=100)),
                ('study_semester', models.PositiveSmallIntegerField(help_text='The program semester this course belongs to (1–8).')),
                ('section', models.CharField(max_length=20)),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'FACULTY'}, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.term')),
            ],
            options={
                'ordering': ['-term__year', 'term__season', 'code', 'section'],
                'constraints': [models.UniqueConstraint(fields=('code', 'section', 'term'), name='uniq_course_code_section_term')],
            },
        ),
    ]
